name: Testing multilines string

on: workflow_dispatch

jobs:
  updating_pr_body:
    runs-on: [ubuntu-latest]
    steps:
    - name: Formatting test-script outcome
      id: format-outcome
      run: |
        our_string="cameraTiltCalib robotGazebo"
        our_list=($our_string)
        markdown_list="<ul>"
        for el in ${our_list[@]}
        do
          markdown_list="$markdown_list <li>el</li>"
        done
        markdown_list="$markdown_list</ul>"
        echo "Result: $markdown_list"
        echo "::set-output name=test_outcome::$markdown_list"
        
    - name: printing
      run: |
              Test script result\:
              "${{ steps.format-outcome.outputs.test_outcome }}"

        
